.TH emissions 1 "January 15, 2019" "Version 0.0" "emissions for WattTime.org API"
.SH NAME
emissions - display current grid data "green" status  using the WattTime.org API

.SH SYNOPSIS
emissions
.OP \-hq
.OP \-debug
.OP \-l location
.OP \-a account
.OP \-p password
.YS
.SH DESCRIPTION
.B emissions
is a command line function to display real time green data from the WattTime.org API.
.PP
.UR https://\:WattTime.org
WattTime home page
.UE
.SH FILES
.I $HOME/.WattTime/account
.RS
Configuration Files
.RE
.I $HOME/.WattTime/ba
.RS
Balancing Authority to use as default
.RE
.SH OPTIONS
.IP -q
Quiet flag - supresses output.  Function returns 0 if green power is true else 1
.IP -a
Account name to use
.IP -p
Password for account
.IP -h
List help for all parameters
.IP -debug
Go into debug mode and display debug and trace information
.SH EXAMPLES
display real time green power information from a balancing authority
.PP
.nf
.RS
.ft B
emissions -l CAISO_NP15 -a accountname -p password
.sp
.RE
.fi
.PP
.PP
.SH BUGS
None known - but this is verion 0.0
.SH AUTHOR
.MT maurice@\:bizzarrisoftware.com
Maurice Bizzarri
.ME
.SH SEE ALSO
griddata, gridregion, makeacct


